#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
WebpageList = [
    # More and more use interactive webpage

    # Trial
    #'999*ted.com',

    '0*nounplus.net',
    # Webby
    #'1*http://projects.two-n.com/world-gender/',
    '1*two-n.com',
    '2*makeitok.org',

    #Brand
    '3*mozilla.org',
    '4*segmentfault.com',
    '5*kameisyouten.ocnk.net',

    #'6*https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_setup/py_intro/py_intro.html#intro',
    '6*docs.opencv.org',
    
    #'7*http://blog.sciencenet.cn/blog.php',
    '7*blog.sciencenet.cn',
    '8*yinwang.org',

    #'9*http://www.richyli.com/tool/loremipsum/',
    '9*richyli.com',
    '10*pxtoem.com',

    '11*labinthewild.org',
    '12*yatani.jp',
    '13*interaction-design.org',
    '14*jlpt.jp',
    '15*pantone.com',
    '16*blog.yitianshijie.net',
    '17*infoq.com',
    '18*techplay.jp'
    #'19*'
]
'''

WebpageList = [
#'999*ted.com',
'0*theboneandjointcenter.com',
'1*mozilla.org',
'2*two-n.com',
'3*segmentfault.com',
'4*makeitok.org',
'5*disney.co.jp',
'6*wikipedia.org',
'7*news.yahoo.co.jp',
'8*huxiu.com',
'9*fangdd.com',
'10*cheshi.com',
'11*humblebundle.com',
'12*theatlantic.com',
'13*superprof.fr',
'14*microsoft.com',
'15*opera.com',
'16*labinthewild.org',
'17*nounplus.net',
'18*richyli.com',
'19*pxtoem.com', 
'20*goofy.photo',
'21*javadrive.jp',
'22*jcodecraeer.com',
'23*hdpfans.com',
'24*jiqimao.tv',
'25*clamav.net',
'26*bootcdn.cn',
'27*runoob.com',
'28*tensorfly.cn',
'29*journaldugeek.com', 
'30*matetranslate.com',
'31*kameisyouten.ocnk.net',
'32*gingerweb.jp',
'33*cp.pocky.jp',
'34*aladdin-aic.com',
'35*ho-ginza.com',
'36*pandayori.com',
'37*sekimoto.dental',
'38*kokage-m.com',
'39*coming-saji.com',
'40*bluewood.bitter.jp',
'41*steakland.jp',
'42*showroomprive.com',
'43*imas-cg.net',
'44*filetender.com',
'45*hexo.io',
'46*yinwang.org',
'47*blog.yitianshijie.net',
'48*yatani.jp',
'49*qiita.com',
'50*52nlp.cn',
'51*guidetojapanese.org',
'52*olderadults.mobi',
'53*blog.whatsapp.com',
'54*stratechery.com',
'55*lomake.fi',
'56*theclinic.cl',
'57*bgmaimuna.com',
'58*0dt.net',
'59*web.ics.purdue.edu',
'60*canon-foundation.jp',
'61*docs.opencv.org',
'62*interaction-design.org',
'63*jlpt.jp',
'64*blog.sciencenet.cn',
'65*pantone.com',
'66*sdtech.co.jp',
'67*news.livedoor.com',
'68*gmo.jp',
'69*tokai-tv.com', 
'70*life-is-tech.com',
'71*bloomberg.co.jp',
'72*cerezo.jp',
'73*tech.nikkeibp.co.jp',
'74*jp.techcrunch.com',
'75*capcom.co.jp',
'76*kenkun-jinja.org',
'77*sankei.com',
'78*tech-jp.co.jp',
'79*tech-camp.in',
'80*hasegawa-heart.com',
'81*techplay.jp',
'82*ubejinja.or.jp',
'83*19lou.com',
'84*jiankang.com',
'85*cps.com.cn',
'86*hea.cn',
'87*jfc.or.jp',
'88*trafst.jp',
'89*infoq.com',
'90*secure.j-bus.co.jp',
'91*jcr.incites.thomsonreuters.com',
'92*dna.fr',
'93*macg.co',
'94*cvpr2018.thecvf.com',
'95*chi2019.acm.org',
'96*swellnet.com',
'97*klex.ru',
'98*kudago.com',
'99*theborneopost.com'
]

suncolor_sequence = ['#FF1E1E', '#FF7215', '#FFBB04', '#FFF72C', '#D1FF3F',
                '#97FF4D', '#1ACD00', '#008930', '#00D3E8', '#27A3FF',
                '#005EFE', '#0200AC', '#9975FF', '#8724FF', '#CD44FF',
                '#FF2ED6']